Update readme
SkillsFundingAgency/das-apprenticeships-web pull request #34
Opened 2024-01-31 11:30 UTC by MichaelYoung1981

2024-02-05 13:58 UTC, tom-gough requested changes

2024-02-05 13:58 UTC, tom-gough commented on README.md
> +The UI should only be dependant on the Apprenticeships Outer API.  If you want to run the application locally you will need to make sure the Outer API is running locally or the configuration is point
Mention inner api here too?

2024-02-21 11:06 UTC, MikeV-TalentConsulting approved these changes

2024-02-26 10:42 UTC, tom-gough approved these changes

2024-08-12 14:29 UTC, tom-gough submitted a review, later dismissed
Approved but added 2 minor comments

2024-08-12 14:29 UTC, tom-gough commented on README.md
> +[![Build Status](https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_apis/build/status/das-apprenticeships-web?branchName=master)](https://dev.azure.com/sfa-gov-uk/Digital%20Apprenti
This is a specific build - should be https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_build?definitionId=3497&_a=summary

2024-08-12 14:29 UTC, tom-gough commented on README.md
> +* Azure Storage Emulator (Azureite)
typo in Azurite

2024-08-12 14:45 UTC, tom-gough approved these changes

2024-08-12 15:17 UTC, merged